version: "3.8"

services:
  backend:
    build: ./backend
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/articdb
      SPRING_DATASOURCE_USERNAME: articuser
      SPRING_DATASOURCE_PASSWORD: articpass

  frontend:
    build: ./frontend
    container_name: angular-app
    ports:
      - "4200:80"

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: articdb
      POSTGRES_USER: articuser
      POSTGRES_PASSWORD: articpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: