--
-- PostgreSQL database dump
--

\restrict pEbBhfY5leLBizX2HyX1w7n93dwxW8Xc7TqzsX5uDcjec5b54E5Os7ljtPdmd7f

-- Dumped from database version 13.21 (Debian 13.21-1.pgdg120+1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: artic
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO artic;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aluguel; Type: TABLE; Schema: public; Owner: artic
--

CREATE TABLE public.aluguel (
    id bigint NOT NULL,
    data_fim date,
    data_inicio date,
    status character varying(255),
    valor_total numeric(38,2),
    carro_id bigint,
    usuario_id bigint
);


ALTER TABLE public.aluguel OWNER TO artic;

--
-- Name: aluguel_id_seq; Type: SEQUENCE; Schema: public; Owner: artic
--

ALTER TABLE public.aluguel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aluguel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carro; Type: TABLE; Schema: public; Owner: artic
--

CREATE TABLE public.carro (
    id bigint NOT NULL,
    ano integer,
    cor character varying(255),
    disponivel_para_aluguel boolean,
    disponivel_para_venda boolean,
    marca character varying(255),
    modelo character varying(255),
    placa character varying(255),
    portas integer,
    preco_aluguel_por_dia numeric(38,2),
    preco_venda numeric(38,2),
    tipo_combustivel character varying(255),
    url_imagem character varying(255)
);


ALTER TABLE public.carro OWNER TO artic;

--
-- Name: carro_id_seq; Type: SEQUENCE; Schema: public; Owner: artic
--

ALTER TABLE public.carro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compra; Type: TABLE; Schema: public; Owner: artic
--

CREATE TABLE public.compra (
    id bigint NOT NULL,
    data_compra date,
    status character varying(255),
    valor_pago numeric(38,2),
    carro_id bigint,
    usuario_id bigint
);


ALTER TABLE public.compra OWNER TO artic;

--
-- Name: compra_id_seq; Type: SEQUENCE; Schema: public; Owner: artic
--

ALTER TABLE public.compra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: artic
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    cpf character varying(255),
    email character varying(255),
    "endereço" character varying(255),
    nome character varying(255),
    senha character varying(255),
    telefone character varying(255)
);


ALTER TABLE public.usuario OWNER TO artic;

--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: artic
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: aluguel; Type: TABLE DATA; Schema: public; Owner: artic
--

COPY public.aluguel (id, data_fim, data_inicio, status, valor_total, carro_id, usuario_id) FROM stdin;
\.


--
-- Data for Name: carro; Type: TABLE DATA; Schema: public; Owner: artic
--

COPY public.carro (id, ano, cor, disponivel_para_aluguel, disponivel_para_venda, marca, modelo, placa, portas, preco_aluguel_por_dia, preco_venda, tipo_combustivel, url_imagem) FROM stdin;
32	2021	Branco	f	t	BMW	\N	DEF5678	5	0.00	285000.00	Diesel	assets/CARcompra/bmw.png
33	2022	Vermelho	f	t	Fiat	\N	MNC3792	4	0.00	90000.00	Gasolina	assets/CARcompra/fiat_mobi_vermelho.png
34	2023	Preto	f	t	Jeep	\N	JRP4935	4	0.00	130000.00	Gasolina	assets/CARcompra/jeep_renegade.png
35	2021	Cinza	f	t	Volkswagen	\N	VWG2021	4	0.00	75000.00	Gasolina	assets/CARcompra/gol_2021.png
36	2024	Azul	f	t	Chevrolet	\N	CHT2424	4	0.00	110000.00	Gasolina	assets/CARcompra/onix_2024.png
37	2022	Prata	f	t	Ford	\N	RGR2022	4	0.00	210000.00	Diesel	assets/CARcompra/ford_ranger.png
47	2021	Preto	t	f	Volkswagen	Onix	BCC5857	4	120.00	0.00	Gasolina	assets/CARaluguel/onix2021preto.png
48	2021	Branco	t	f	Volkswagen	Gol	LSF5646	4	92.00	0.00	Gasolina	assets/CARaluguel/volkswagen2021branco.png
49	2024	Branco	t	f	Fiat	Cronos	FGO9317	4	105.00	0.00	Gasolina	assets/CARaluguel/fiat cronos 2024.png
50	2023	Branco	t	f	Hyundai	HB20	LLM1796	4	108.00	0.00	Gasolina	assets/CARaluguel/Hyundai HB20 2023.png
51	2023	Branco	t	f	Renault	Kwid	OFG85417	4	87.00	0.00	Gasolina	assets/CARaluguel/renault kwid 2024.png
53	2024	Branco	t	f	Toyota	Corolla	MNC3792	4	129.00	0.00	Gasolina	assets/CARaluguel/ToyotaCorolla2024.png
\.


--
-- Data for Name: compra; Type: TABLE DATA; Schema: public; Owner: artic
--

COPY public.compra (id, data_compra, status, valor_pago, carro_id, usuario_id) FROM stdin;
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: artic
--

COPY public.usuario (id, cpf, email, "endereço", nome, senha, telefone) FROM stdin;
\.


--
-- Name: aluguel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: artic
--

SELECT pg_catalog.setval('public.aluguel_id_seq', 1, false);


--
-- Name: carro_id_seq; Type: SEQUENCE SET; Schema: public; Owner: artic
--

SELECT pg_catalog.setval('public.carro_id_seq', 53, true);


--
-- Name: compra_id_seq; Type: SEQUENCE SET; Schema: public; Owner: artic
--

SELECT pg_catalog.setval('public.compra_id_seq', 1, false);


--
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: artic
--

SELECT pg_catalog.setval('public.usuario_id_seq', 1, false);


--
-- Name: aluguel aluguel_pkey; Type: CONSTRAINT; Schema: public; Owner: artic
--

ALTER TABLE ONLY public.aluguel
    ADD CONSTRAINT aluguel_pkey PRIMARY KEY (id);


--
-- Name: carro carro_pkey; Type: CONSTRAINT; Schema: public; Owner: artic
--

ALTER TABLE ONLY public.carro
    ADD CONSTRAINT carro_pkey PRIMARY KEY (id);


--
-- Name: compra compra_pkey; Type: CONSTRAINT; Schema: public; Owner: artic
--

ALTER TABLE ONLY public.compra
    ADD CONSTRAINT compra_pkey PRIMARY KEY (id);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: artic
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- Name: compra fk2qiqsmv4x66hro4yrs1yr07ox; Type: FK CONSTRAINT; Schema: public; Owner: artic
--

ALTER TABLE ONLY public.compra
    ADD CONSTRAINT fk2qiqsmv4x66hro4yrs1yr07ox FOREIGN KEY (carro_id) REFERENCES public.carro(id);


--
-- Name: aluguel fkgbaqjdlyv6f04170ixuri6yfp; Type: FK CONSTRAINT; Schema: public; Owner: artic
--

ALTER TABLE ONLY public.aluguel
    ADD CONSTRAINT fkgbaqjdlyv6f04170ixuri6yfp FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: compra fkk39qkguq7uka81tdyvhrkvppf; Type: FK CONSTRAINT; Schema: public; Owner: artic
--

ALTER TABLE ONLY public.compra
    ADD CONSTRAINT fkk39qkguq7uka81tdyvhrkvppf FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: aluguel fkpiu0oam8nqjiycuw3jinbw1rc; Type: FK CONSTRAINT; Schema: public; Owner: artic
--

ALTER TABLE ONLY public.aluguel
    ADD CONSTRAINT fkpiu0oam8nqjiycuw3jinbw1rc FOREIGN KEY (carro_id) REFERENCES public.carro(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: artic
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict pEbBhfY5leLBizX2HyX1w7n93dwxW8Xc7TqzsX5uDcjec5b54E5Os7ljtPdmd7f

